#! /bin/sh
# Add to your $HOME/.bazaar/bazaar.conf to section:
# [DEFAULT]
# the line:
# editor = /usr/local/libexec/xworld/bzr-joe-editor
#
# This can also be done with the following command:
# $ sed -ie '/^\[DEFAULT]$/a editor = /usr/local/libexec/xworld/bzr-joe-editor' ~/.bazaar/bazaar.conf
l=`locale | sed -e 's,^LANG=,,; t; d'`
cs=${l##*.}
test -x"$cs" != x"$l" || cs=
l=en_US.${cs:-utf8}
exec joe -language "$l" -rmargin 73 -wordwrap -- "$@"
