#! /bin/sh
# Add to your $HOME/.bazaar/bazaar.conf to section:
# [DEFAULT]
# the line:
# editor = /usr/local/libexec/xworld/bzr-joe-editor
ol=`locale | sed -e 's,^LANG=,,; t; d'`
LANG=en_US.utf8
LC_CTYPE=$ol
LC_MONETARY=$ol
LC_MESSAGES=$ol
LC_PAPER=$ol
LC_NAME=$ol
LC_ADDRESS=$ol
LC_MEASUREMENT=$ol
LC_IDENTIFICATION=$ol
unset LC_ALL
export LANG LC_CTYPE LC_MONETARY LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS
export LC_MEASUREMENT LC_IDENTIFICATION
exec joe -rmargin 73 -wordwrap -- "$@"
